

#ifndef LAS_VERSION_MAJOR
#  define LAS_VERSION_MAJOR    1
#  define LAS_VERSION_MINOR    0
#  define LAS_VERSION_REV      0
#  define LAS_VERSION_BUILD    0
#endif

#ifndef LAS_VERSION_NUM
#  define LAS_VERSION_NUM      (LAS_VERSION_MAJOR*1000+LAS_VERSION_MINOR*100+LAS_VERSION_REV*10+LAS_VERSION_BUILD)
#endif

#ifndef LAS_RELEASE_DATE
#  define LAS_RELEASE_DATE     20071203
#endif
#ifndef LAS_RELEASE_NAME
#  define LAS_RELEASE_NAME     "1.0.0"
#endif
