libLAS API Reference: liblas::Index Class Reference
liblas::Index Class Reference
#include <index.hpp>
Public Member Functions
Index ()
Index (IndexData const &ParamSrc)
~Index ()
Index (Index const &other)
Copy constructor.
Index & operator= (Index const &rhs)
Assignment operator.
bool IndexFailed (void) const
bool IndexReady (void) const
bool Prep (IndexData const &ParamSrc)
const std::vector< uint32_t > & Filter (IndexData &ParamSrc)
IndexIterator * Filter (IndexData const &ParamSrc, uint32_t ChunkSize)
IndexIterator * Filter (double LowFilterX, double HighFilterX, double LowFilterY, double HighFilterY, double LowFilterZ, double HighFilterZ, uint32_t ChunkSize)
IndexIterator * Filter (Bounds< double > const &BoundsSrc, uint32_t ChunkSize)
double GetMinX (void) const
double GetMaxX (void) const
double GetMinY (void) const
double GetMaxY (void) const
double GetMinZ (void) const
double GetMaxZ (void) const
double GetRangeX (void) const
double GetRangeY (void) const
double GetRangeZ (void) const
Bounds< double > const & GetBounds (void) const
uint32_t GetPointRecordsCount (void) const
uint32_t GetCellsX (void) const
uint32_t GetCellsY (void) const
uint32_t GetCellsZ (void) const
uint32_t GetDataVLR_ID (void) const
double GetCellSizeZ (void) const
FILE * GetDebugger (void) const
bool GetReadOnly (void) const
bool GetStandaloneIndex (void) const
bool GetForceNewIndex (void) const
uint32_t GetMaxMemoryUsage (void) const
int GetDebugOutputLevel (void) const
Header * GetPointHeader (void)
Header * GetIndexHeader (void)
Reader * GetReader (void) const
Reader * GetIndexReader (void) const
const char * GetTempFileName (void) const
const char * GetIndexAuthorStr (void) const
const char * GetIndexCommentStr (void) const
const char * GetIndexDateStr (void) const
uint8_t GetVersionMajor (void) const
uint8_t GetVersionMinor (void) const
void SetDataVLR_ID (uint32_t DataVLR_ID)
void SetIndexAuthorStr (const char *ias)
void SetIndexCommentStr (const char *ics)
void SetIndexDateStr (const char *ids)
void SetMinX (double minX)
void SetMaxX (double maxX)
void SetMinY (double minY)
void SetMaxY (double maxY)
void SetMinZ (double minZ)
void SetMaxZ (double maxZ)
void SetPointRecordsCount (uint32_t prc)
void SetCellsX (uint32_t cellsX)
void SetCellsY (uint32_t cellsY)
void SetCellsZ (uint32_t cellsZ)
Constructor & Destructor Documentation
liblas::Index::Index ()
liblas::Index::Index (IndexData const & ParamSrc)
liblas::Index::~Index ()
liblas::Index::Index (Index const & other)
Copy constructor.
Member Function Documentation
const std::vector<uint32_t>& liblas::Index::Filter (IndexData & ParamSrc)
IndexIterator* liblas::Index::Filter (IndexData const & ParamSrc, uint32_t ChunkSize)
IndexIterator* liblas::Index::Filter (double LowFilterX, double HighFilterX, double LowFilterY, double HighFilterY, double LowFilterZ, double HighFilterZ, uint32_t ChunkSize)
IndexIterator* liblas::Index::Filter (Bounds< double > const & BoundsSrc, uint32_t ChunkSize)
Bounds<double> const& liblas::Index::GetBounds (void) const inline
double liblas::Index::GetCellSizeZ (void) const inline
uint32_t liblas::Index::GetCellsX (void) const inline
uint32_t liblas::Index::GetCellsY (void) const inline
uint32_t liblas::Index::GetCellsZ (void) const inline
uint32_t liblas::Index::GetDataVLR_ID (void) const inline
FILE* liblas::Index::GetDebugger (void) const inline
int liblas::Index::GetDebugOutputLevel (void) const inline
bool liblas::Index::GetForceNewIndex (void) const inline
const char* liblas::Index::GetIndexAuthorStr (void) const
const char* liblas::Index::GetIndexCommentStr (void) const
const char* liblas::Index::GetIndexDateStr (void) const
Header* liblas::Index::GetIndexHeader (void) inline
Reader* liblas::Index::GetIndexReader (void) const inline
uint32_t liblas::Index::GetMaxMemoryUsage (void) const inline
double liblas::Index::GetMaxX (void) const inline
References liblas::Bounds< T >::max().
double liblas::Index::GetMaxY (void) const inline
References liblas::Bounds< T >::max().
double liblas::Index::GetMaxZ (void) const inline
References liblas::Bounds< T >::max().
double liblas::Index::GetMinX (void) const inline
References liblas::Bounds< T >::min().
double liblas::Index::GetMinY (void) const inline
References liblas::Bounds< T >::min().
double liblas::Index::GetMinZ (void) const inline
References liblas::Bounds< T >::min().
Header* liblas::Index::GetPointHeader (void) inline
uint32_t liblas::Index::GetPointRecordsCount (void) const inline
double liblas::Index::GetRangeX (void) const inline
double liblas::Index::GetRangeY (void) const inline
double liblas::Index::GetRangeZ (void) const inline
Reader* liblas::Index::GetReader (void) const inline
bool liblas::Index::GetReadOnly (void) const inline
bool liblas::Index::GetStandaloneIndex (void) const inline
const char* liblas::Index::GetTempFileName (void) const inline
uint8_t liblas::Index::GetVersionMajor (void) const inline
uint8_t liblas::Index::GetVersionMinor (void) const inline
bool liblas::Index::IndexFailed (void) const inline
bool liblas::Index::IndexReady (void) const inline
Index& liblas::Index::operator= (Index const & rhs)
Assignment operator.
bool liblas::Index::Prep (IndexData const & ParamSrc)
void liblas::Index::SetCellsX (uint32_t cellsX) inline
void liblas::Index::SetCellsY (uint32_t cellsY) inline
void liblas::Index::SetCellsZ (uint32_t cellsZ) inline
void liblas::Index::SetDataVLR_ID (uint32_t DataVLR_ID) inline
void liblas::Index::SetIndexAuthorStr (const char * ias) inline
void liblas::Index::SetIndexCommentStr (const char * ics) inline
void liblas::Index::SetIndexDateStr (const char * ids) inline
void liblas::Index::SetMaxX (double maxX) inline
References liblas::Bounds< T >::max().
void liblas::Index::SetMaxY (double maxY) inline
References liblas::Bounds< T >::max().
void liblas::Index::SetMaxZ (double maxZ) inline
References liblas::Bounds< T >::max().
void liblas::Index::SetMinX (double minX) inline
References liblas::Bounds< T >::min().
void liblas::Index::SetMinY (double minY) inline
References liblas::Bounds< T >::min().
void liblas::Index::SetMinZ (double minZ) inline
References liblas::Bounds< T >::min().
void liblas::Index::SetPointRecordsCount (uint32_t prc) inline
The documentation for this class was generated from the following file:
/mnt/d/libLAS.wsl/include/liblas/index.hpp