libLAS API Reference: liblas::IndexData Class Reference
liblas::IndexData Class Reference
#include <index.hpp>
Public Member Functions
IndexData (void)
IndexData (Index const &index)
bool SetInitialValues (std::istream *ifs=0, Reader *reader=0, std::ostream *ofs=0, Reader *idxreader=0, const char *tmpfilenme=0, const char *indexauthor=0, const char *indexcomment=0, const char *indexdate=0, double zbinht=0.0, uint32_t maxmem=LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel=0, bool readonly=0, bool writestandaloneindex=0, bool forcenewindex=0, FILE *debugger=0)
bool SetBuildEmbedValues (Reader *reader, std::ostream *ofs, const char *tmpfilenme, const char *indexauthor=0, const char *indexcomment=0, const char *indexdate=0, double zbinht=0.0, uint32_t maxmem=LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel=0, FILE *debugger=0)
bool SetBuildAloneValues (Reader *reader, std::ostream *ofs, const char *tmpfilenme, const char *indexauthor=0, const char *indexcomment=0, const char *indexdate=0, double zbinht=0.0, uint32_t maxmem=LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel=0, FILE *debugger=0)
bool SetReadEmbedValues (Reader *reader, int debugoutputlevel=0, FILE *debugger=0)
bool SetReadAloneValues (Reader *reader, Reader *idxreader, int debugoutputlevel=0, FILE *debugger=0)
bool SetReadOrBuildEmbedValues (Reader *reader, std::ostream *ofs, const char *tmpfilenme, const char *indexauthor=0, const char *indexcomment=0, const char *indexdate=0, double zbinht=0.0, uint32_t maxmem=LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel=0, FILE *debugger=0)
bool SetReadOrBuildAloneValues (Reader *reader, std::ostream *ofs, const char *tmpfilenme, const char *indexauthor=0, const char *indexcomment=0, const char *indexdate=0, double zbinht=0.0, uint32_t maxmem=LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel=0, FILE *debugger=0)
bool SetFilterValues (double LowFilterX, double HighFilterX, double LowFilterY, double HighFilterY, double LowFilterZ, double HighFilterZ, Index const &index)
bool SetFilterValues (Bounds< double > const &src, Index const &index)
IndexData (IndexData const &other)
Copy constructor.
IndexData & operator= (IndexData const &rhs)
Assignment operator.
double GetCellSizeZ (void) const
FILE * GetDebugger (void) const
bool GetReadOnly (void) const
bool GetStandaloneIndex (void) const
bool GetForceNewIndex (void) const
uint32_t GetMaxMemoryUsage (void) const
Reader * GetReader (void) const
int GetDebugOutputLevel (void) const
const char * GetTempFileName (void) const
const char * GetIndexAuthorStr (void) const
const char * GetIndexCommentStr (void) const
const char * GetIndexDateStr (void) const
double GetMinFilterX (void) const
double GetMaxFilterX (void) const
double GetMinFilterY (void) const
double GetMaxFilterY (void) const
double GetMinFilterZ (void) const
double GetMaxFilterZ (void) const
void ClampFilterBounds (Bounds< double > const &m_bounds)
void SetReader (Reader *reader)
void SetIStream (std::istream *ifs)
void SetOStream (std::ostream *ofs)
void SetTmpFileName (const char *tmpfilenme)
void SetIndexAuthor (const char *indexauthor)
void SetIndexComment (const char *indexcomment)
void SetIndexDate (const char *indexdate)
void SetCellSizeZ (double cellsizez)
void SetMaxMem (uint32_t maxmem)
void SetDebugOutputLevel (int debugoutputlevel)
void SetReadOnly (bool readonly)
void SetStandaloneIndex (bool writestandaloneindex)
void SetDebugger (FILE *debugger)
Protected Member Functions
void SetIterator (IndexIterator *setIt)
IndexIterator * GetIterator (void)
Protected Attributes
Reader * m_reader
Reader * m_idxreader
IndexIterator * m_iterator
Bounds< double > m_filter
std::istream * m_ifs
std::ostream * m_ofs
const char * m_tempFileName
const char * m_indexAuthor
const char * m_indexComment
const char * m_indexDate
double m_cellSizeZ
double m_LowXBorderPartCell
double m_HighXBorderPartCell
double m_LowYBorderPartCell
double m_HighYBorderPartCell
int32_t m_LowXCellCompletelyIn
int32_t m_HighXCellCompletelyIn
int32_t m_LowYCellCompletelyIn
int32_t m_HighYCellCompletelyIn
int32_t m_LowZCellCompletelyIn
int32_t m_HighZCellCompletelyIn
int32_t m_LowXBorderCell
int32_t m_HighXBorderCell
int32_t m_LowYBorderCell
int32_t m_HighYBorderCell
int32_t m_LowZBorderCell
int32_t m_HighZBorderCell
uint32_t m_maxMemoryUsage
int m_debugOutputLevel
bool m_noFilterX
bool m_noFilterY
bool m_noFilterZ
bool m_readOnly
bool m_writestandaloneindex
bool m_forceNewIndex
bool m_indexValid
FILE * m_debugger
Friends
class Index
class IndexIterator
Constructor & Destructor Documentation
liblas::IndexData::IndexData (void)
liblas::IndexData::IndexData (Index const & index)
liblas::IndexData::IndexData (IndexData const & other)
Copy constructor.
Member Function Documentation
void liblas::IndexData::ClampFilterBounds (Bounds< double > const & m_bounds)
double liblas::IndexData::GetCellSizeZ (void) const inline
FILE* liblas::IndexData::GetDebugger (void) const inline
int liblas::IndexData::GetDebugOutputLevel (void) const inline
bool liblas::IndexData::GetForceNewIndex (void) const inline
const char* liblas::IndexData::GetIndexAuthorStr (void) const
const char* liblas::IndexData::GetIndexCommentStr (void) const
const char* liblas::IndexData::GetIndexDateStr (void) const
IndexIterator* liblas::IndexData::GetIterator (void) inline protected
double liblas::IndexData::GetMaxFilterX (void) const inline
References liblas::Bounds< T >::max().
double liblas::IndexData::GetMaxFilterY (void) const inline
References liblas::Bounds< T >::max().
double liblas::IndexData::GetMaxFilterZ (void) const inline
References liblas::Bounds< T >::max().
uint32_t liblas::IndexData::GetMaxMemoryUsage (void) const inline
double liblas::IndexData::GetMinFilterX (void) const inline
References liblas::Bounds< T >::min().
double liblas::IndexData::GetMinFilterY (void) const inline
References liblas::Bounds< T >::min().
double liblas::IndexData::GetMinFilterZ (void) const inline
References liblas::Bounds< T >::min().
Reader* liblas::IndexData::GetReader (void) const inline
bool liblas::IndexData::GetReadOnly (void) const inline
bool liblas::IndexData::GetStandaloneIndex (void) const inline
const char* liblas::IndexData::GetTempFileName (void) const inline
IndexData& liblas::IndexData::operator= (IndexData const & rhs)
Assignment operator.
bool liblas::IndexData::SetBuildAloneValues (Reader * reader, std::ostream * ofs, const char * tmpfilenme, const char * indexauthor = 0, const char * indexcomment = 0, const char * indexdate = 0, double zbinht = 0.0, uint32_t maxmem = LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel = 0, FILE * debugger = 0)
bool liblas::IndexData::SetBuildEmbedValues (Reader * reader, std::ostream * ofs, const char * tmpfilenme, const char * indexauthor = 0, const char * indexcomment = 0, const char * indexdate = 0, double zbinht = 0.0, uint32_t maxmem = LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel = 0, FILE * debugger = 0)
void liblas::IndexData::SetCellSizeZ (double cellsizez) inline
void liblas::IndexData::SetDebugger (FILE * debugger) inline
void liblas::IndexData::SetDebugOutputLevel (int debugoutputlevel) inline
bool liblas::IndexData::SetFilterValues (double LowFilterX, double HighFilterX, double LowFilterY, double HighFilterY, double LowFilterZ, double HighFilterZ, Index const & index)
bool liblas::IndexData::SetFilterValues (Bounds< double > const & src, Index const & index)
void liblas::IndexData::SetIndexAuthor (const char * indexauthor) inline
void liblas::IndexData::SetIndexComment (const char * indexcomment) inline
void liblas::IndexData::SetIndexDate (const char * indexdate) inline
bool liblas::IndexData::SetInitialValues (std::istream * ifs = 0, Reader * reader = 0, std::ostream * ofs = 0, Reader * idxreader = 0, const char * tmpfilenme = 0, const char * indexauthor = 0, const char * indexcomment = 0, const char * indexdate = 0, double zbinht = 0.0, uint32_t maxmem = LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel = 0, bool readonly = 0, bool writestandaloneindex = 0, bool forcenewindex = 0, FILE * debugger = 0)
void liblas::IndexData::SetIStream (std::istream * ifs) inline
void liblas::IndexData::SetIterator (IndexIterator * setIt) inline protected
void liblas::IndexData::SetMaxMem (uint32_t maxmem) inline
void liblas::IndexData::SetOStream (std::ostream * ofs) inline
bool liblas::IndexData::SetReadAloneValues (Reader * reader, Reader * idxreader, int debugoutputlevel = 0, FILE * debugger = 0)
bool liblas::IndexData::SetReadEmbedValues (Reader * reader, int debugoutputlevel = 0, FILE * debugger = 0)
void liblas::IndexData::SetReader (Reader * reader) inline
void liblas::IndexData::SetReadOnly (bool readonly) inline
bool liblas::IndexData::SetReadOrBuildAloneValues (Reader * reader, std::ostream * ofs, const char * tmpfilenme, const char * indexauthor = 0, const char * indexcomment = 0, const char * indexdate = 0, double zbinht = 0.0, uint32_t maxmem = LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel = 0, FILE * debugger = 0)
bool liblas::IndexData::SetReadOrBuildEmbedValues (Reader * reader, std::ostream * ofs, const char * tmpfilenme, const char * indexauthor = 0, const char * indexcomment = 0, const char * indexdate = 0, double zbinht = 0.0, uint32_t maxmem = LIBLAS_INDEX_MAXMEMDEFAULT, int debugoutputlevel = 0, FILE * debugger = 0)
void liblas::IndexData::SetStandaloneIndex (bool writestandaloneindex) inline
void liblas::IndexData::SetTmpFileName (const char * tmpfilenme) inline
Friends And Related Function Documentation
friend class Index friend
friend class IndexIterator friend
Member Data Documentation
double liblas::IndexData::m_cellSizeZ protected
FILE* liblas::IndexData::m_debugger protected
int liblas::IndexData::m_debugOutputLevel protected
Bounds<double> liblas::IndexData::m_filter protected
bool liblas::IndexData::m_forceNewIndex protected
int32_t liblas::IndexData::m_HighXBorderCell protected
double liblas::IndexData::m_HighXBorderPartCell protected
int32_t liblas::IndexData::m_HighXCellCompletelyIn protected
int32_t liblas::IndexData::m_HighYBorderCell protected
double liblas::IndexData::m_HighYBorderPartCell protected
int32_t liblas::IndexData::m_HighYCellCompletelyIn protected
int32_t liblas::IndexData::m_HighZBorderCell protected
int32_t liblas::IndexData::m_HighZCellCompletelyIn protected
Reader* liblas::IndexData::m_idxreader protected
std::istream* liblas::IndexData::m_ifs protected
const char* liblas::IndexData::m_indexAuthor protected
const char* liblas::IndexData::m_indexComment protected
const char* liblas::IndexData::m_indexDate protected
bool liblas::IndexData::m_indexValid protected
IndexIterator* liblas::IndexData::m_iterator protected
int32_t liblas::IndexData::m_LowXBorderCell protected
double liblas::IndexData::m_LowXBorderPartCell protected
int32_t liblas::IndexData::m_LowXCellCompletelyIn protected
int32_t liblas::IndexData::m_LowYBorderCell protected
double liblas::IndexData::m_LowYBorderPartCell protected
int32_t liblas::IndexData::m_LowYCellCompletelyIn protected
int32_t liblas::IndexData::m_LowZBorderCell protected
int32_t liblas::IndexData::m_LowZCellCompletelyIn protected
uint32_t liblas::IndexData::m_maxMemoryUsage protected
bool liblas::IndexData::m_noFilterX protected
bool liblas::IndexData::m_noFilterY protected
bool liblas::IndexData::m_noFilterZ protected
std::ostream* liblas::IndexData::m_ofs protected
Reader* liblas::IndexData::m_reader protected
bool liblas::IndexData::m_readOnly protected
const char* liblas::IndexData::m_tempFileName protected
bool liblas::IndexData::m_writestandaloneindex protected
The documentation for this class was generated from the following file:
/mnt/d/libLAS.wsl/include/liblas/index.hpp