var DOCUMENTATION_OPTIONS = {
    URL_ROOT: '',
    VERSION: 'SET(CPACK_PACKAGE_VERSION_MAJOR ${LIBLAS_VERSION_MAJOR}.SET(CPACK_PACKAGE_VERSION_PATCH ${LIBLAS_VERSION_MINOR}.set(VERSION ${LIBLAS_VERSION_MAJOR}.${LIBLAS_VERSION_MINOR}.${LIBLAS_VERSION_PATCH}',
    LANGUAGE: 'None',
    COLLAPSE_INDEX: false,
    FILE_SUFFIX: '.html',
    HAS_SOURCE: true,
    SOURCELINK_SUFFIX: '.txt'
};